Team.new(team_name: 'Buccaneers', email: "test1@test.com", password_digest: 'test1')
Team.new(team_name: 'Eager Boomerangs', email: 'test2@test.com', password_digest: 'test2')
Team.new(team_name: 'Powerful Warthogs', email: 'test3@test.com', password_digest: 'test3')

=begin
Player.new(name: 'Eri', posittion: 'Goalkeeper', games: 2, goals: 0, saves: 4, assists: 0, blocks: 2, shots: 1 0, interceptions: 1 1, passes: 35 10, red_cards: 0 0, yellow_cards: 01)
Player.new(name: 'Alryd', posittion: 'Center-Left', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 0, yellow_cards: 00)
Player.new(name: 'Karveth', posittion: 'Center-Right', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 0, yellow_cards: 00)
Player.new(name: 'Grodayrth', posittion: 'Left-Fullback', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 0, yellow_cards: 00)
Player.new(name: 'Irgarth', posittion: 'Right-Fullback', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 0, yellow_cards: 00)
Player.new(name: 'Boimram', posittion: 'Defensive Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Nammienth', posittion: 'Right-Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Omrurrer', posittion: 'Left-Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Puvorim', posittion: 'Center-Midfielder', games: 2, goals: 0, saves: 0, assists: 1, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Jalzrinta', posittion: 'Forward', games: 2, goals: 2, saves: 0, assists: 1, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Asin', posittion: 'Attacking-Midfielder', games: 2, goals: 2, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)

Player.new(name: 'Pirphal', posittion: 'Goalkeeper', games: 2, goals: 2, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Cohnal', posittion: 'Center-Left', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Sharian', posittion: 'Center-Right', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Malon', posittion: 'Left-Fullback', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Taranath', posittion: 'Right-Fullback', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Tamnaeth', posittion: 'Defensive Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Voron', posittion: 'Right-Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Wyrran', posittion: 'Left-Midfielder', games: 2, goals: 0, saves: 0, assists: 1, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Shandalar', posittion: 'Center-Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Tyrael', posittion: 'Forward', games: 2, goals: 2, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Chalsarda', posittion: 'Attacking-Midfielder', games: 2, goals: 1, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)

Player.new(name: 'Oun', posittion: 'Goalkeeper', games: 2, goals: 0, saves: 1, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Ukx', posittion: 'Center-Left', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Gerk', posittion: 'Center-Right', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Ouz', posittion: 'Left-Fullback', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Kuorg', posittion: 'Right-Fullback', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Kraxerrg', posittion: 'Defensive-Midfielder', games: 2, goals: 1, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Ghuotozz', posittion: 'Right-Midfielder', games: 2, goals: 1, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Miryr', posittion: 'Left-Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Tuzzok', posittion: 'Center-Midfielder', games: 2, goals: 0, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Thruhyrrg', posittion: 'Forward', games: 2, goals: 0, saves: 0, assists:1 , blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
Player.new(name: 'Dyn', posittion: 'Attacking-Midfielder', games: 2, goals: 1, saves: 0, assists: 0, blocks: , shots: 1 , interceptions: 1 , passes: 35 , red_cards: 0 , yellow_cards: 0)
=end
